image: docker:stable

variables:
  MYSQL_DATABASE: django
  # MYSQL_USER: root
  # MYSQL_PASSWORD: root
  MYSQL_ROOT_PASSWORD: root
  # MYSQL_HOST: "mysql"
  # MYSQL_PORT: "3306"
  # DATABASE_URL: mysql+pymysql://root:root@127.0.0.1:8889/django

services:
  - docker:dind

# connect:
#   image: mysql:latest
#   script:
#     - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

test:
  image: python:latest
  script:
    - python3 -V                                   # Print out Python version for debugging
    - pip3 -V
    - export LC_ALL=C.UTF-8                        # Tell Python to use UTF-8
    - export LANG=C.UTF-8
    - pip3 install pipenv
    - pipenv install --dev
    - pipenv run python manage.py test
