version: "3"
services:
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
     - MYSQL_ROOT_PASSWORD
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - backend
  web:
    environment:
      - DJANGO_ENV
      - DJANGO_SECRET_KEY
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_PORT
    image: "chem-lab-server:${DJANGO_TAG}"
    build: .
    container_name: chem-lab-server
    ports:
      - "${DJANGO_PORT}:8000"
    restart: on-failure
    networks:
      - frontend
      - backend

volumes:
  mysql:

networks:
  frontend:
  backend:
