# Generated by Django 2.1.4 on 2018-12-04 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Assignment')),
            ],
            options={
                'db_table': 'api_assignment_entry',
            },
        ),
        migrations.CreateModel(
            name='AssignmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_assignment_template',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwuid', models.CharField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=10)),
                ('enroll_key', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Instructor')),
            ],
            options={
                'db_table': 'api_labgroup',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwuid', models.CharField(max_length=7)),
                ('labgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.LabGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField()),
                ('raw_input', models.TextField()),
                ('assignment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AssignmentEntry')),
            ],
            options={
                'db_table': 'api_task_entry',
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('prompt', models.TextField()),
                ('prompt_format', models.CharField(max_length=50, null=True)),
                ('image_urls', models.TextField(null=True)),
                ('attempts_allowed', models.IntegerField(null=True)),
                ('numeric_accuracy', models.IntegerField(null=True)),
                ('numeric_only', models.BooleanField()),
                ('assignment_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AssignmentTemplate')),
            ],
            options={
                'db_table': 'api_task_template',
            },
        ),
        migrations.AddField(
            model_name='taskentry',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TaskTemplate'),
        ),
        migrations.AddField(
            model_name='assignmenttemplate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
        migrations.AddField(
            model_name='assignmententry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AssignmentTemplate'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='labgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktemplate',
            unique_together={('assignment_template', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='labgroup',
            unique_together={('course', 'group_name', 'term')},
        ),
    ]
