# Generated by Django 2.1.2 on 2018-10-23 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Assignment')),
            ],
            options={
                'db_table': 'api_assignment_entry',
            },
        ),
        migrations.CreateModel(
            name='AssignmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_assignment_template',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwuid', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('enroll_key', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Instructor')),
            ],
            options={
                'db_table': 'api_lab_group',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwuid', models.CharField(max_length=7)),
                ('lab_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('assignment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AssignmentEntry')),
            ],
            options={
                'db_table': 'api_task_entry',
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image_urls', models.TextField(null=True)),
                ('points', models.FloatField()),
                ('attempts_allowed', models.IntegerField(null=True)),
                ('text_input', models.TextField(null=True)),
                ('numeric_input', models.TextField(null=True)),
                ('numeric_accuracy', models.IntegerField(null=True)),
                ('multiple_choice', models.TextField(null=True)),
                ('assignment_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AssignmentTemplate')),
            ],
            options={
                'db_table': 'api_task_template',
            },
        ),
        migrations.AddField(
            model_name='taskentry',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TaskTemplate'),
        ),
        migrations.AddField(
            model_name='assignmenttemplate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
        migrations.AddField(
            model_name='assignmententry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AssignmentTemplate'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lab_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabGroup'),
        ),
    ]
