# Generated by Django 2.1.2 on 2018-12-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmententry',
            name='grade',
        ),
    ]
