# Generated by Django 2.1.2 on 2018-11-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labgroup',
            unique_together={('course', 'group_name', 'term')},
        ),
    ]
